/**
 * Atlas ResourcePage - Server Component
 *
 * Dual-mode page handling the two deep levels of the knowledge graph:
 *
 *   Level 2 - Topic Hub  (/resources/{topic-slug})
 *     Fetches topic + articles via getTopicWithArticles() in one round-trip.
 *     Builds CollectionPage schema with contentStyle  @type mapping,
 *     speakableText injection, and curated article ordering.
 *
 *   Level 3 - Single Article (/resources/{topic-slug}/{article-slug})
 *     Uses article.__jsonLd (CMS-generated by generateLdSchema hook) so the
 *     correct @type (HowTo / ScholarlyArticle / Article) is always used.
 *     Renders: keyTakeaways callout, speakableText, additionalSources, scored
 *     related articles (topic match 100pts + tag overlap 10pts each).
 */

import Link from "next/link";
import Image from "next/image";
import React from "react";
import type { PageProps } from "@/lib/types";
import type { Article, Topic, MediaItem } from "@/lib/api";
import { getTopicWithArticles, getArticles, getArticleBySlug, getTopics } from "@/lib/api";
import { Breadcrumbs } from "@/components/Breadcrumbs";
import { ArticleCard } from "@/components/ArticleCard";
import { RichTextRenderer } from "@/components/RichTextRenderer";
import { JsonLd } from "@/components/JsonLd";
import { notFound } from "next/navigation";

// - Schema helpers -

const CONTENT_STYLE_TYPE: Record<string, string> = {
  guide: "HowTo",
  explainer: "ScholarlyArticle",
  concept: "Article",
};

/**
 * Builds the CollectionPage JSON-LD for a Topic hub page.
 * - Maps contentStyle  Schema.org @type
 * - Injects speakableText as SpeakableSpecification
 * - Attaches DefinedTerm mainEntity for concept-style articles
 * - Respects curatedArticles ordering if editor has curated a list
 */
function buildCollectionPageSchema(topic: Topic, articles: Article[], siteUrl: string): Record<string, unknown> {
  // Resolve curated order if editors have selected specific articles
  let targetArticles: Article[];
  const curated = topic.curatedArticles;
  if (Array.isArray(curated) && curated.length > 0 && typeof curated[0] === "object") {
    const curatedIds = curated.map((a) => (typeof a === "object" ? (a as Article).id : a));
    const byId = Object.fromEntries(articles.map((a) => [a.id, a]));
    targetArticles = curatedIds.map((id) => byId[id as number]).filter(Boolean) as Article[];
    // Append any articles not in curated list
    const curatedSet = new Set(curatedIds);
    articles.filter((a) => !curatedSet.has(a.id)).forEach((a) => targetArticles.push(a));
  } else {
    targetArticles = articles.slice(0, 8);
  }

  const itemListElement = targetArticles.map((article, i) => {
    const schemaType = CONTENT_STYLE_TYPE[article.contentStyle ?? ""] ?? "Article";
    const item: Record<string, unknown> = {
      "@type": schemaType,
      headline: article.metaTitle || article.title,
      url: `${siteUrl}/resources/${topic.slug}/${article.slug}`,
    };

    if (article.aiSummary || article.metaDescription) {
      item.description = article.aiSummary || article.metaDescription;
    }

    // Concept articles: attach DefinedTerm for semantic entity precision
    if (article.contentStyle === "concept" && article.primaryEntity) {
      item.mainEntity = {
        "@type": "DefinedTerm",
        name: article.primaryEntity,
        ...(article.aiSummary ? { description: article.aiSummary } : {}),
        ...(article.primaryEntityUrl ? { sameAs: article.primaryEntityUrl } : {}),
      };
    }

    return { "@type": "ListItem", position: i + 1, item };
  });

  const schema: Record<string, unknown> = {
    "@context": "https://schema.org",
    "@type": "CollectionPage",
    name: topic.name,
    description: topic.description || `Explore our curated archive of ${topic.name.toLowerCase()} resources.`,
    url: `${siteUrl}/resources/${topic.slug}`,
    about: { "@type": "Thing", name: topic.name },
  };

  if (topic.speakableText) {
    schema.speakable = {
      "@type": "SpeakableSpecification",
      cssSelector: [".geo-speakable"],
    };
  }

  if (itemListElement.length > 0) {
    schema.hasPart = { "@type": "ItemList", numberOfItems: itemListElement.length, itemListElement };
  }

  return schema;
}

// - Related article scoring -

function scoreRelated(candidate: Article, currentArticle: Article): number {
  let score = 0;
  const currentTopicId = typeof currentArticle.topic === "object" && currentArticle.topic ? currentArticle.topic.id : currentArticle.topic;
  const candTopicId = typeof candidate.topic === "object" && candidate.topic ? candidate.topic.id : candidate.topic;
  if (candTopicId === currentTopicId) score += 100;

  const currentTagIds = Array.isArray(currentArticle.tags)
    ? currentArticle.tags.map((t) => (typeof t === "object" ? t.id : t))
    : [];
  const candTagIds = Array.isArray(candidate.tags)
    ? candidate.tags.map((t) => (typeof t === "object" ? t.id : t))
    : [];
  candTagIds.forEach((id) => { if (currentTagIds.includes(id)) score += 10; });
  // Recency tiebreaker (tiny weight)
  score += new Date(candidate.createdAt).getTime() / 10000000000000;
  return score;
}

// - Media helpers -

function resolveMedia(m: MediaItem | number | null | undefined): MediaItem | null {
  if (!m || typeof m === "number") return null;
  return m;
}

function formatDate(iso: string): string {
  return new Intl.DateTimeFormat("en-ZA", { year: "numeric", month: "long", day: "numeric" }).format(new Date(iso));
}

// - Main Component -

export default async function ResourcePage({ config, path, noCache }: PageProps) {
  const tenant = config.tenant.slug;
  const siteUrl = `https://${tenant}.chameleon.services`;
  const siteName = config.settings?.siteName ?? config.tenant.name;

  // path[0] = "resources", path[1] = topic-slug, path[2] = article-slug
  const topicSlug = path[1];
  const articleSlug = path[2];

  if (!topicSlug) notFound();

  if (articleSlug) {
    return renderArticle({ tenant, siteUrl, siteName, topicSlug, articleSlug, config, noCache });
  }

  return renderTopicHub({ tenant, siteUrl, siteName, topicSlug, noCache });
}

// - Level 2: Topic Hub -

type TopicHubProps = {
  tenant: string; siteUrl: string; siteName: string;
  topicSlug: string; noCache: boolean;
};

async function renderTopicHub({ tenant, siteUrl, siteName, topicSlug, noCache }: TopicHubProps) {
  const result = await getTopicWithArticles(tenant, topicSlug, noCache);
  if (!result) notFound();

  const { topic, articles: articlesRes } = result;
  const articles: Article[] = articlesRes?.docs ?? [];

  if (!topic) notFound();

  const heroImage = resolveMedia(topic.headerImage as MediaItem | number | null | undefined);

  const breadcrumbs = [
    { label: "Home", href: "/" },
    { label: "Resources", href: "/resources" },
    { label: topic.name },
  ];

  const schema = buildCollectionPageSchema(topic, articles, siteUrl);

  const BreadcrumbSchema: Record<string, unknown> = {
    "@context": "https://schema.org",
    "@type": "BreadcrumbList",
    itemListElement: [
      { "@type": "ListItem", position: 1, name: "Home", item: siteUrl },
      { "@type": "ListItem", position: 2, name: "Resources", item: `${siteUrl}/resources` },
      { "@type": "ListItem", position: 3, name: topic.name, item: `${siteUrl}/resources/${topicSlug}` },
    ],
  };

  const featured = articles[0] ?? null;
  const remaining = articles.slice(1);

  return (
    <>
      <JsonLd data={BreadcrumbSchema} />
      <JsonLd data={schema} />

      {/* Dark Hero with optional header image */}
      <section className="atlas-topic-hero" style={{ position: "relative", overflow: "hidden" }}>
        {heroImage && (
          <div style={{ position: "absolute", inset: 0, zIndex: 0, opacity: 0.25 }}>
            <Image src={heroImage.url} alt={heroImage.alt ?? topic.name} fill style={{ objectFit: "cover" }} />
          </div>
        )}
        <div className="atlas-container" style={{ position: "relative", zIndex: 1 }}>
          <Breadcrumbs items={breadcrumbs} baseUrl={siteUrl} />
          <div style={{ marginTop: "var(--atlas-spacing-lg)" }}>
            <span style={{ fontSize: "2.5rem", display: "block", marginBottom: "var(--atlas-spacing-sm)" }}>
              {typeof topic.icon === "string" ? topic.icon : ""}
            </span>
            <h1 className="atlas-h1" style={{ color: "#fff" }}>{topic.name}</h1>
            {(topic.description || topic.shortDescription) && (
              <p className="atlas-body-lg" style={{ marginTop: "var(--atlas-spacing-sm)", opacity: 0.8, maxWidth: 660, color: "#fff" }}>
                {topic.description || topic.shortDescription}
              </p>
            )}
            {/* GEO: voice assistant answer hidden visually but valid for SpeakableSpecification */}
            {topic.speakableText && (
              <p className="geo-speakable" style={{ position: "absolute", width: 1, height: 1, overflow: "hidden", clip: "rect(0,0,0,0)" }}>
                {topic.speakableText}
              </p>
            )}
          </div>
          <p className="atlas-caption" style={{ marginTop: "var(--atlas-spacing-md)", opacity: 0.6, color: "#fff" }}>
            {articles.length} article{articles.length !== 1 ? "s" : ""}
          </p>
        </div>
      </section>

      <div className="atlas-container atlas-section-sm">
        {articles.length === 0 ? (
          <div className="atlas-card-flat" style={{ padding: "var(--atlas-spacing-2xl)", textAlign: "center" }}>
            <p className="atlas-body" style={{ opacity: 0.6 }}>No articles have been published in this topic yet.</p>
          </div>
        ) : (
          <>
            {/* Featured Article */}
            {featured && (
              <Link
                href={`/resources/${topicSlug}/${featured.slug}`}
                className="atlas-card atlas-topic-featured atlas-fade-in"
                style={{ display: "grid", textDecoration: "none", color: "inherit", overflow: "hidden", marginBottom: "var(--atlas-spacing-2xl)" }}
              >
                {resolveMedia(featured.heroImage) && (
                  <div style={{ position: "relative", aspectRatio: "21/9", overflow: "hidden" }}>
                    <Image
                      src={resolveMedia(featured.heroImage)!.url}
                      alt={resolveMedia(featured.heroImage)?.alt ?? featured.title}
                      fill sizes="100vw"
                      style={{ objectFit: "cover" }}
                      priority
                    />
                  </div>
                )}
                <div style={{ padding: "var(--atlas-spacing-lg)" }}>
                  <div style={{ display: "flex", gap: "var(--atlas-spacing-sm)", marginBottom: "var(--atlas-spacing-sm)", flexWrap: "wrap" }}>
                    <span className="atlas-badge">Featured</span>
                    {featured.contentStyle && (
                      <span className="atlas-badge" style={{ opacity: 0.7 }}>
                        {featured.contentStyle === "guide" ? "How-To Guide" : featured.contentStyle === "explainer" ? "Explainer" : "Concept"}
                      </span>
                    )}
                  </div>
                  <h2 className="atlas-h3" style={{ marginTop: "var(--atlas-spacing-xs)" }}>{featured.title}</h2>
                  {featured.excerpt && (
                    <p className="atlas-body" style={{ marginTop: "var(--atlas-spacing-sm)", opacity: 0.7 }}>{featured.excerpt}</p>
                  )}
                  {featured.aiSummary && (
                    <p className="atlas-caption" style={{ marginTop: "var(--atlas-spacing-sm)", opacity: 0.6, fontStyle: "italic" }}>
                      {featured.aiSummary}
                    </p>
                  )}
                  <div className="atlas-caption" style={{ marginTop: "var(--atlas-spacing-sm)", opacity: 0.5 }}>
                    {featured.readTime && `${featured.readTime} min read`}
                    {featured.readTime && featured.publishedAt && "  "}
                    {featured.publishedAt && formatDate(featured.publishedAt)}
                  </div>
                </div>
              </Link>
            )}

            {/* Article Grid */}
            {remaining.length > 0 && (
              <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fill, minmax(300px, 1fr))", gap: "var(--atlas-spacing-xl)" }}>
                {remaining.map((article) => (
                  <ArticleCard
                    key={article.id}
                    article={article}
                    basePath={`/resources/${topicSlug}`}
                    className="atlas-card atlas-fade-in"
                  />
                ))}
              </div>
            )}
          </>
        )}
      </div>
    </>
  );
}

// - Level 3: Single Article -

type ArticleViewProps = {
  tenant: string; siteUrl: string; siteName: string;
  topicSlug: string; articleSlug: string;
  config: PageProps["config"]; noCache: boolean;
};

async function renderArticle({ tenant, siteUrl, siteName, topicSlug, articleSlug, config, noCache }: ArticleViewProps) {
  // Fetch article + all topic articles in parallel (for related scoring)
  const [article, topicsRes, relatedRes] = await Promise.all([
    getArticleBySlug(tenant, articleSlug, noCache),
    getTopics(tenant, noCache),
    getArticles({ tenant, section: "resources", limit: 30 }, noCache),
  ]);

  if (!article) notFound();

  const topics = topicsRes?.docs ?? [];
  const topicObj = topics.find((t) => t.slug === topicSlug);
  const topicName = topicObj?.name ?? topicSlug;

  // Related articles - scored by topic match + tag overlap
  const allOtherArticles = (relatedRes?.docs ?? []).filter((a) => a.id !== article.id);
  const scored = allOtherArticles
    .map((a) => ({ article: a, score: scoreRelated(a, article) }))
    .filter((x) => x.score > 0)
    .sort((a, b) => b.score - a.score);
  // Fall back to most recent if no scored matches
  const relatedArticles = (scored.length > 0 ? scored.map((x) => x.article) : allOtherArticles).slice(0, 5);

  const heroImage = resolveMedia(article.heroImage);

  const breadcrumbs = [
    { label: "Home", href: "/" },
    { label: "Resources", href: "/resources" },
    { label: topicName, href: `/resources/${topicSlug}` },
    { label: article.title },
  ];

  // BreadcrumbList JSON-LD
  const breadcrumbSchema: Record<string, unknown> = {
    "@context": "https://schema.org",
    "@type": "BreadcrumbList",
    itemListElement: [
      { "@type": "ListItem", position: 1, name: "Resources", item: `${siteUrl}/resources` },
      { "@type": "ListItem", position: 2, name: topicName, item: `${siteUrl}/resources/${topicSlug}` },
      { "@type": "ListItem", position: 3, name: article.title, item: `${siteUrl}/resources/${topicSlug}/${article.slug}` },
    ],
  };

  // Primary article schema - use CMS-generated __jsonLd if available,
  // fall back to a basic Article schema built locally.
  const articleSchemas: Record<string, unknown>[] = article.__jsonLd
    ? (Array.isArray(article.__jsonLd) ? article.__jsonLd : [article.__jsonLd])
    : [buildFallbackArticleSchema(article, siteUrl, siteName, topicSlug, config)];

  const headings = extractHeadings(article.content);
  const isUpdated = article.createdAt && article.updatedAt
    && (new Date(article.updatedAt).getTime() - new Date(article.createdAt).getTime() > 86400000);

  const hasKeyTakeaways = Array.isArray(article.keyTakeaways) && article.keyTakeaways.length > 0;
  const hasSources = Array.isArray(article.additionalSources) && article.additionalSources.length > 0;

  return (
    <>
      <JsonLd data={breadcrumbSchema} />
      {articleSchemas.map((schema, i) => <JsonLd key={i} data={schema} />)}

      <div className="atlas-container" style={{ paddingTop: "1.5rem", paddingBottom: "4rem" }}>
        <Breadcrumbs items={breadcrumbs} baseUrl={siteUrl} />

        {/* Article layout: content + sidebar */}
        <div className="atlas-article-layout">

          {/* - Main content - */}
          <article>
            <header className="atlas-article-header">
              {/* Content type badge */}
              <div style={{ display: "flex", gap: "var(--atlas-spacing-sm)", marginBottom: "var(--atlas-spacing-sm)", flexWrap: "wrap" }}>
                <Link href={`/resources/${topicSlug}`} className="atlas-badge" style={{ textDecoration: "none" }}>
                  {topicName}
                </Link>
                {article.contentStyle && (
                  <span className="atlas-badge" style={{ opacity: 0.7 }}>
                    {article.contentStyle === "guide" ? "How-To Guide" : article.contentStyle === "explainer" ? "Explainer" : "Concept"}
                  </span>
                )}
              </div>

              <h1 className="atlas-h1" style={{ marginTop: "var(--atlas-spacing-sm)" }}>{article.title}</h1>

              {/* Meta row */}
              <div className="atlas-article-meta">
                {article.author && <span style={{ fontWeight: 600 }}>{typeof article.author === 'object' && 'name' in article.author ? article.author.name : typeof article.author === 'string' ? article.author : null}</span>}
                {article.author && (article.publishedAt || article.readTime) && <span style={{ opacity: 0.3 }}>·</span>}
                {(isUpdated ? article.updatedAt : article.publishedAt) && (
                  <time dateTime={isUpdated ? article.updatedAt : article.publishedAt} className="atlas-caption" style={{ opacity: 0.6 }}>
                    {isUpdated ? "Updated: " : ""}{formatDate((isUpdated ? article.updatedAt : article.publishedAt)!)}
                  </time>
                )}
                {article.readTime && (
                  <span className="atlas-caption" style={{ opacity: 0.6 }}>{article.readTime} min read</span>
                )}
              </div>

              {/* AI Summary (GEO abstract) */}
              {article.aiSummary && (
                <div className="atlas-article-ai-summary" data-speakable>
                  {article.speakableText
                    ? <p>{article.speakableText}</p>
                    : <p>{article.aiSummary}</p>
                  }
                </div>
              )}
            </header>

            {/* Hero Image */}
            {heroImage && (
              <div style={{ position: "relative", aspectRatio: "16/9", borderRadius: "var(--atlas-radius-lg)", overflow: "hidden", marginTop: "var(--atlas-spacing-xl)" }}>
                <Image src={heroImage.url} alt={heroImage.alt ?? article.title} fill sizes="(max-width: 768px) 100vw, 65vw" style={{ objectFit: "cover" }} priority />
              </div>
            )}

            {/* Key Takeaways callout */}
            {hasKeyTakeaways && (
              <div className="atlas-article-takeaways" data-speakable>
                <h2 className="atlas-article-takeaways-title">Key Takeaways</h2>
                <ul className="atlas-article-takeaways-list">
                  {article.keyTakeaways!.map((item, i) => (
                    <li key={i}>{item.point}</li>
                  ))}
                </ul>
              </div>
            )}

            {/* Article body */}
            {article.content != null && (
              <div className="atlas-article-body" style={{ marginTop: "var(--atlas-spacing-2xl)" }}>
                <RichTextRenderer content={article.content as Record<string, unknown>} className="atlas-body" />
              </div>
            )}

            {/* Sources & Citations */}
            {hasSources && (
              <footer className="atlas-article-sources">
                <h3 className="atlas-h6" style={{ marginBottom: "var(--atlas-spacing-sm)" }}>Sources &amp; Citations</h3>
                <ol style={{ paddingLeft: "1.25rem", margin: 0 }}>
                  {article.additionalSources!.map((source, i) => (
                    <li key={i} style={{ fontSize: "0.8125rem", opacity: 0.7, marginBottom: "0.25rem" }}>
                      <a href={source.url} target="_blank" rel="noopener noreferrer" style={{ color: "var(--brand-primary, #2d6a4f)" }}>
                        {source.label}
                      </a>
                    </li>
                  ))}
                </ol>
              </footer>
            )}
          </article>

          {/* - Sidebar - */}
          <aside>
            {/* Table of Contents */}
            {headings.length > 0 && (
              <div className="atlas-article-toc">
                <h3 className="atlas-h6" style={{ marginBottom: "var(--atlas-spacing-sm)" }}>Contents</h3>
                <nav>
                  <ul style={{ listStyle: "none", padding: 0, margin: 0, fontSize: "0.8125rem", lineHeight: 2 }}>
                    {headings.map((h, i) => (
                      <li key={i} style={{ paddingLeft: h.level === 3 ? "1rem" : 0 }}>
                        <span className="atlas-caption" style={{ opacity: 0.7 }}>{h.text}</span>
                      </li>
                    ))}
                  </ul>
                </nav>
              </div>
            )}

            {/* Related Resources */}
            {relatedArticles.length > 0 && (
              <div style={{ marginTop: "var(--atlas-spacing-xl)" }}>
                <h3 className="atlas-h6" style={{ marginBottom: "var(--atlas-spacing-md)" }}>Related Resources</h3>
                <div style={{ display: "flex", flexDirection: "column", gap: "var(--atlas-spacing-sm)" }}>
                  {relatedArticles.map((related) => {
                    const relatedTopic = related.topic && typeof related.topic === "object" ? related.topic : null;
                    return (
                      <Link
                        key={related.id}
                        href={`/resources/${relatedTopic?.slug ?? topicSlug}/${related.slug}`}
                        className="atlas-card-flat"
                        style={{ display: "block", padding: "var(--atlas-spacing-sm) var(--atlas-spacing-md)", textDecoration: "none", color: "inherit" }}
                      >
                        {relatedTopic && relatedTopic.slug !== topicSlug && (
                          <span className="atlas-badge" style={{ marginBottom: 4, display: "block", fontSize: "0.6875rem" }}>{relatedTopic.name}</span>
                        )}
                        <h4 style={{ margin: 0, fontSize: "0.8125rem", fontWeight: 600, lineHeight: 1.4 }}>{related.title}</h4>
                        {related.readTime && (
                          <span className="atlas-caption" style={{ opacity: 0.5, marginTop: 2, display: "block" }}>{related.readTime} min read</span>
                        )}
                      </Link>
                    );
                  })}
                </div>
              </div>
            )}
          </aside>
        </div>
      </div>
    </>
  );
}

// - Fallback article schema (when __jsonLd not available) -

function buildFallbackArticleSchema(
  article: Article,
  siteUrl: string,
  siteName: string,
  topicSlug: string,
  config: PageProps["config"],
): Record<string, unknown> {
  const schemaType = CONTENT_STYLE_TYPE[article.contentStyle ?? ""] ?? "Article";
  const heroImage = resolveMedia(article.heroImage);
  const schema: Record<string, unknown> = {
    "@context": "https://schema.org",
    "@type": schemaType,
    headline: article.metaTitle || article.title,
    description: article.metaDescription || article.aiSummary || article.excerpt,
    url: `${siteUrl}/resources/${topicSlug}/${article.slug}`,
    datePublished: article.publishedAt ?? article.createdAt,
    dateModified: article.updatedAt,
    ...(heroImage && { image: heroImage.url }),
    ...(article.author && { author: { "@type": "Person", name: article.author } }),
    publisher: {
      "@type": "Organization",
      name: siteName,
      ...(config.settings?.logo && { logo: { "@type": "ImageObject", url: (config.settings.logo as { url: string }).url } }),
    },
    inLanguage: "en",
    isAccessibleForFree: true,
    ...(article.aiSummary ? { abstract: article.aiSummary } : {}),
    ...(article.primaryEntityUrl ? { sameAs: article.primaryEntityUrl } : {}),
    ...(article.primaryEntity ? { about: article.primaryEntity } : {}),
    ...(article.speakableText
      ? { speakable: { "@type": "SpeakableSpecification", cssSelector: ["[data-speakable]"] } }
      : {}),
  };

  if (Array.isArray(article.keyTakeaways) && article.keyTakeaways.length > 0) {
    if (article.contentStyle === "guide") {
      schema.step = article.keyTakeaways.map((t) => ({ "@type": "HowToStep", text: t.point }));
    } else {
      schema.hasPart = {
        "@type": "ItemList",
        itemListElement: article.keyTakeaways.map((t, i) => ({ "@type": "ListItem", position: i + 1, name: t.point })),
      };
    }
  }

  return schema;
}

// - Heading extraction for Table of Contents -

type Heading = { level: number; text: string };

function extractHeadings(content: unknown): Heading[] {
  if (!content || typeof content !== "object") return [];
  const headings: Heading[] = [];

  function walk(node: Record<string, unknown>) {
    if (node.type === "heading" && typeof node.tag === "string") {
      const level = parseInt((node.tag as string).replace("h", ""), 10);
      if (level >= 2 && level <= 3) {
        const text = extractText(node);
        if (text) headings.push({ level, text });
      }
    }
    const root = node.root as Record<string, unknown> | undefined;
    const children = node.children ?? root?.children;
    if (Array.isArray(children)) {
      for (const child of children) {
        if (child && typeof child === "object") walk(child as Record<string, unknown>);
      }
    }
  }

  walk(content as Record<string, unknown>);
  return headings;
}

function extractText(node: Record<string, unknown>): string {
  if (typeof node.text === "string") return node.text;
  if (Array.isArray(node.children)) {
    return node.children
      .map((c: unknown) => (c && typeof c === "object" ? extractText(c as Record<string, unknown>) : ""))
      .join("");
  }
  return "";
}
